---
- name: Testing andrewrothstein.gomplate
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'gomplate --version'
      ansible.builtin.command: gomplate --version
      changed_when: false
      register: gomplate_test_output
    - name: Output from 'gomplate --version'
      ansible.builtin.debug:
        msg: '{{ gomplate_test_output.stdout }}'
