---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ gomplate_url }} to {{ gomplate_install_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ gomplate_url }}'
    dest: '{{ gomplate_install_exe }}'
    checksum: '{{ gomplate_checksum }}'
    mode: '755'
- name: Linking {{ gomplate_link }} to {{ gomplate_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ gomplate_install_exe }}'
    dest: '{{ gomplate_link }}'
    state: link
